# Generated by Django 3.1 on 2020-09-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200909_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInstanceUpdate',
        ),
    ]
