# Generated by Django 3.1 on 2020-09-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_bookinstanceupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstanceupdate',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookinstanceupdate',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstanceupdate',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='bookinstanceupdate',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='bookinstanceupdate',
            name='imprint',
        ),
        migrations.RemoveField(
            model_name='bookinstanceupdate',
            name='status',
        ),
        migrations.AlterField(
            model_name='bookinstanceupdate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
